apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: demo
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: demo-container
        image: laxmireddy870113/backend:v1
        ports:
        - containerPort: 5000

